export { customNextConfig } from './config/nextConfig.js'
export { Link, type LinkProps } from './link.js'
export { Image, type ImageProps } from './image.js'
export { notFound } from './notFound.js'
export type { Metadata } from 'next'
