name: Schema Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
    branches: [main]
  workflow_dispatch:

jobs:
  schema-check:
    name: 'Schema • ${{ matrix.site }}'
    runs-on: ubuntu-latest
    environment: apollo
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}

    strategy:
      matrix:
        include:
          - site: lundi-main
            secret_name: DATOCMS_ACCESS_TOKEN

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.36.2 | sh

          # Add Rover to the $GITHUB_PATH so it can be used in another step
          # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Check whoami
        run: rover config whoami
      - name: Validate ${{ matrix.site }} schema
        env:
          DATOCMS_ACCESS_TOKEN: ${{ secrets[matrix.secret_name] }}
        run: |
          rover graph introspect https://graphql.datocms.com \
            --header "Authorization: Bearer ${{ env.DATOCMS_ACCESS_TOKEN }}" \
          | rover subgraph check vandiessen-mono-graph@current \
            --schema - \
            --name lundi-bleu-dato-cms
      - name: Generate SDL
        env:
          DATOCMS_ACCESS_TOKEN: ${{ secrets[matrix.secret_name] }}
        run: |
          rover graph introspect https://graphql.datocms.com \
              --header "Authorization: Bearer ${{ env.DATOCMS_ACCESS_TOKEN }}" \
            > ./packages/data/src/generated/${{ matrix.site }}.graphql
      - name: Publishing lundi-bleu-dato-cms schema
        run: |
          rover subgraph publish vandiessen-mono-graph@current --name lundi-bleu-dato-cms --schema ./packages/data/src/generated/${{ matrix.site }}.graphql
