name: Schema Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
    branches: [main]
  workflow_dispatch:

jobs:
  Schema-check:
    runs-on: ubuntu-latest
    environment: apollo
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
      DATOCMS_ACCESS_TOKEN: ${{ secrets.DATOCMS_ACCESS_TOKEN }}
      APOLLO_VCS_COMMIT: ${{ github.event.pull_request.head.sha }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.19.1 | sh

          # Add Rover to the $GITHUB_PATH so it can be used in another step
          # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
          echo "$HOME/.rover/bin" >> $GITHUB_PATH
      - name: Validating subgraph schema changes
        if: ${{ env.DATOCMS_ACCESS_TOKEN != '' }}
        run: |
          rover graph introspect https://graphql.datocms.com --header "Authorization: Bearer ${{ env.DATOCMS_ACCESS_TOKEN }}" \
            | rover subgraph check vandiessen-mono@current \
            --schema - --name Lundi-Bleu-Dato-CMS
      - name: Downloading datocms schema
        if: ${{ env.DATOCMS_ACCESS_TOKEN != '' }}
        run: |
          rover graph introspect https://graphql.datocms.com --header "Authorization: Bearer ${{ env.DATOCMS_ACCESS_TOKEN }}" \
          > ./packages/graphql/src/generated/datocms.graphql
      - name: Publishing Lundi-Bleu-Dato-CMS schema
        if: ${{ env.APOLLO_KEY != '' }}
        run: |
          rover subgraph publish vandiessen-mono@current --name datocms --schema ./packages/graphql/src/generated/datocms.graphql
